services:
  - type: web
    name: elyor-bot
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python elyor_bot1.py"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9
